name: Trigger Blog Site Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get latest commit SHA
        id: get-sha
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "Latest commit SHA: $COMMIT_SHA"
      
      - name: Trigger webhook
        run: |
          echo "Triggering webhook with commit SHA: ${{ steps.get-sha.outputs.commit_sha }}"
          
          response=$(curl -s -w "\n%{http_code}" -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.ACTION_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "event_type": "update-posts-sha",
              "client_payload": {
                "commit_sha": "${{ steps.get-sha.outputs.commit_sha }}"
              }
            }' \
            https://api.github.com/repos/PhaTLa/myBlogSite/dispatches)
          
          # Extract response body and status code
          response_body=$(echo "$response" | head -n -1)
          status_code=$(echo "$response" | tail -n 1)
          
          echo "HTTP Status Code: $status_code"
          echo "Response Body: $response_body"
          
          if [ "$status_code" -eq 204 ]; then
            echo "✅ Webhook triggered successfully (HTTP 204)"
          else
            echo "❌ Webhook failed with status code: $status_code"
            echo "Response: $response_body"
            exit 1
          fi